### ISSUE TITLE
Not work on tizen

### ISSUE THREAD

**Issue by mohammadavr** [oasenov/SamsungTV_IPTV#1]
Hi 
I am test your code on samsung tv with tizen os .
I created template project and inserted your code on it .
I made a widget and installed it on the TV .
But just not working just loading .... appears on screen , 
Could you help me ? 
Regards 
Mohammad

**Comment by oasenov** [comment]
Hi @mohammadavr , it was a hobby project I was using around 2013, TizenOS, tizen SDKs have evolved a lot every since, so did the hardware. I never had time to maintain that mini project
