### ISSUE TITLE
channels.js

### ISSUE THREAD

**Issue by DolleDries** [oasenov/SamsungTV_IPTV#2]
What does this look like? I'm a newbe in javascript...

**Comment by oasenov** [comment]
Hi @DolleDries  it was a hobby project done years ago, channels.js  I thought i had an example of it but apparently it is missing, 

content should be like below, an array of playable channels. Note that this url is fed to TV's player. 
[
			{name:'ABC News', url:'http://abclive.abcnews.com/i/abc_live4@136330/index_1200_av-b.m3u8'},
			{name:'Euro news', url:'http://ewns-hls-b-cdn.hexaglobe.net/1259b4185677ea20e8736c0f0182e14a/58fc8503/euronews_eng.smil/playlist.m3u8'}
		 ];
